<?php
/**
 * @file
 * Code for the Radar search feature.
 */

include_once 'radar_search.features.inc';

/**
 * Implements hook_permissions().
 */
function radar_search_permission() {
  return array(
    'search content' => array(
      'title' => t('Search content'),
      'description' => t('Replacement for core search permission. Used by services seach api.'),
    ),
  );
}

/**
 * Implements hook_facetapi_url_processors().
 */
function radar_search_facetapi_url_processors() {
  return array(
    'radar_search_pretty_paths' => array(
      'handler' => array(
        'label' => t('Radar pretty paths'),
        'class' => 'FacetapiUrlProcessorPrettyPathsRadar',
      ),
    ),
  );
}

/**
 * Implements hook_facetapi_searcher_info_alter().
 *
 * Alter search descriptions to add our class in place of pretty_paths.
 *
 * @param array &$searcher_info
 *   The return values of hook_facetapi_searcher_info() implementations.
 */
function radar_search_facetapi_searcher_info_alter(array &$searcher_info) {
  foreach ($searcher_info as &$info) {
    // Activate pretty paths optionally per searcher, as configured.
    $id = 'facetapi_pretty_paths_searcher_' . $info['name'];
    $info['url processor'] = variable_get($id) ? 'radar_search_pretty_paths' : 'standard';
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Just clarify our alteration of pretty paths.
 */
function radar_search_form_facetapi_pretty_paths_admin_form_alter(&$form, $form_state) {
  $form['searcher']['#title'] .= ' ' . t('(Radar altered)');
}

/**
* Implements hook_views_data_alter()
*/
function radar_search_views_data_alter(&$data) {
  foreach (search_api_index_load_multiple(FALSE) as $index) {
    $key = 'search_api_index_' . $index->machine_name;
    $type_info = search_api_get_item_type_info($index->item_type);
    if ($type_info['entity_type'] == 'node') {
      $table = &$data[$key];
      $table['clone_node'] = array(
        'field' => array(
          'title' => t('Clone link'),
          'help' => t('Provide a simple link to clone the node.'),
          'handler' => 'views_handler_field_node_link_clone',
        ),
      );
    }
  }
}
