<?php
// $Id: og_facets.install,v 1.1 2008/04/24 22:55:14 delius Exp $

/**
 * Implementation of hook_uninstall().
 */
function og_facets_uninstall() {
  if (db_table_exists('faceted_search_variables')) {
    db_query("DELETE FROM {faceted_search_variables} WHERE name = 'og_facets_excluded_types'");
  }
  if (db_table_exists('faceted_search_filters')) {
    db_query("DELETE FROM {faceted_search_filters} WHERE filter_key = 'og'");
  }
}