<?php
/**
 * @file
 * Code for the radar_listings_group feature.
 */

include_once 'radar_listings_group.features.inc';

/**
 * Implements hook_radar_entity_integration().
 */
function radar_listings_group_radar_entity_integration() {
  return array(
    'node' => array(
      'listings_group' => array(
        'is_group_content' => FALSE,
        'is_group' => TRUE,
        'exclude_radar_follow' => TRUE,
      ),
    ),
  );
}
