<?php
/**
 * @file
 * Code for the Event ical feature.
 */

include_once 'radar_event_ical.features.inc';

/**
 * Implements hook_feeds_presave().
 *
 * Correct timezone such that the date field timezone is the timezone of the event.
 * iCal parser respects the timezone on a time (usually UTC Z), in preference to the
 * X-WR-TIMEZONE.
 */
function radar_event_ical_feeds_presave($source, $entity, $item, $entity_id) {
  if (!is_object($entity)) {
    return;
  }
  $wrapper = entity_metadata_wrapper('node', $entity);
  if (!count($wrapper->field_date_time)) {
    // no date.
    return;
  }
  if (!count($wrapper->field_offline)) {
    // no location.
    return;
  }

  // Retrieve the first date's timezone and compare with the first related
  // location's timezone.
  $location_timezone = $wrapper->field_offline[0]->field_timezone->value();
  try {
    $timezone = new DateTimeZone($location_timezone);
  }
  catch(Exception $e) {
    watchdog_exception('radar_event', $e);
    return;
  }
  $info = field_info_field('field_date_time');
  // Check each date instance and make consistent local time events.
  foreach ($wrapper->field_date_time as $key => $date_wrapper) {
    $data = $date_wrapper->raw();
    if ($data['timezone'] != $location_timezone) {
      if (isset($data['date'])) {
          //if (isset($data['value2']) && date_is_all_day($data['value'], $data['value2'])) {
        $date = new DateTime($data['value'], new DateTimezone($data['timezone']));
        $date->setTimezone($timezone);
        $data['value'] = $date->format(date_type_format($info['type']));
        $data['date']->setTimezone($timezone);
        $data['offset'] = $data['date']->getOffset();
        if (isset($data['value2'])) {
          $date2 = new DateTime($data['value2'], new DateTimezone($data['timezone']));
          $date2->setTimezone($timezone);
          $data['value2'] = $date2->format(date_type_format($info['type']));
          $data['offset2'] = $data['date']->getOffset();
        }
        $data['timezone'] = $location_timezone;
        $date_wrapper->set($data);
      }
    }
    $data = $date_wrapper->raw();
  }
}
