<?php
/**
 * @file
 * radar_vocabularies.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function radar_vocabularies_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'free shop',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '0b9e8d1f-d51d-4d32-b984-2dba1099e0fa',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'category',
  );
  $terms[] = array(
    'name' => 'meeting',
    'description' => '',
    'format' => 'rich_text_editor',
    'weight' => 0,
    'uuid' => '20a888f9-54c1-4767-8af1-40de3d1d2636',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'category',
  );
  $terms[] = array(
    'name' => 'membership fee',
    'description' => '',
    'format' => 'rich_text_editor',
    'weight' => 2,
    'uuid' => '272bf5a8-2127-465f-9e19-f6049a58cf4b',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'price',
  );
  $terms[] = array(
    'name' => '3-5 CHF',
    'description' => '',
    'format' => 'rich_text_editor',
    'weight' => 7,
    'uuid' => '277c8fae-1727-4fd4-b6c8-b12ca32cac98',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'price',
  );
  $terms[] = array(
    'name' => 'bar/cafe',
    'description' => 'somewhere were you can go for a drink and to meet people',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '2a56c4d7-eb98-4f96-9ac6-d383a1af5ce8',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'category',
  );
  $terms[] = array(
    'name' => 'course/workshop',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '2a7f6975-4c01-4777-8611-dffe0306c06f',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'category',
  );
  $terms[] = array(
    'name' => 'theater',
    'description' => '',
    'format' => 'rich_text_editor',
    'weight' => 0,
    'uuid' => '3a8606d4-95ac-4941-a2ae-05835e5903dc',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'category',
  );
  $terms[] = array(
    'name' => 'less than 3 CHF',
    'description' => '',
    'format' => 'rich_text_editor',
    'weight' => 6,
    'uuid' => '3b38fe7d-3641-4b7f-b559-d38f7637ed29',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'price',
  );
  $terms[] = array(
    'name' => 'less than 3 €',
    'description' => '',
    'format' => 'rich_text_editor',
    'weight' => 3,
    'uuid' => '5ea06cf1-c46b-46e3-9a39-556fced3b35e',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'price',
  );
  $terms[] = array(
    'name' => 'exhibition',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '5ef858bd-178c-4d89-9a96-742b0e3f250f',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'category',
  );
  $terms[] = array(
    'name' => 'film',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '68197b93-2ece-4b0f-9a76-d9e99bda2603',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'category',
  );
  $terms[] = array(
    'name' => '3-5 €',
    'description' => '',
    'format' => 'rich_text_editor',
    'weight' => 4,
    'uuid' => '6f4101f4-cd9b-49f2-91a3-203d2b47a3ed',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'price',
  );
  $terms[] = array(
    'name' => 'radio',
    'description' => '',
    'format' => 'rich_text_editor',
    'weight' => 0,
    'uuid' => '7a5fcb74-5a3b-49fa-9ffd-e4ca1a3eb936',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'category',
  );
  $terms[] = array(
    'name' => 'other',
    'description' => '',
    'format' => 'rich_text_editor',
    'weight' => 9,
    'uuid' => '7e7e09ce-138d-4c92-8e45-a5156c2a7176',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'price',
  );
  $terms[] = array(
    'name' => 'discussion/presentation',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8463bb01-e974-4785-9c2d-b95d87c9ee2d',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'category',
  );
  $terms[] = array(
    'name' => 'children',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8a5a0f5a-a8a7-4849-800b-ee9938b6d421',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'category',
  );
  $terms[] = array(
    'name' => 'food',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => '8e846372-fa86-4cb2-87d1-f24da784ec6b',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'category',
  );
  $terms[] = array(
    'name' => 'by donation',
    'description' => '',
    'format' => 'rich_text_editor',
    'weight' => 1,
    'uuid' => '9d943d0c-e2bf-408e-9110-4bfb044f60c0',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'price',
  );
  $terms[] = array(
    'name' => 'party',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'b89e871f-c923-4f66-a7ba-a34bc9ccce5b',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'category',
  );
  $terms[] = array(
    'name' => 'more than 5 €',
    'description' => '',
    'format' => 'rich_text_editor',
    'weight' => 5,
    'uuid' => 'cbaef9d1-d187-4eb6-9e16-91ef45ab7aaa',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'price',
  );
  $terms[] = array(
    'name' => 'more than 5 CHF',
    'description' => '',
    'format' => 'rich_text_editor',
    'weight' => 8,
    'uuid' => 'cf950118-303f-4439-8429-17a77882ef27',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'price',
  );
  $terms[] = array(
    'name' => 'free',
    'description' => '',
    'format' => 'rich_text_editor',
    'weight' => 0,
    'uuid' => 'dfb542fc-f5b5-491d-87be-95f1c0813d57',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'price',
  );
  $terms[] = array(
    'name' => 'action/protest/camp',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'e85a688d-03ac-4008-a3cb-1adb7e8f718a',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'category',
  );
  $terms[] = array(
    'name' => 'advice/help/office hours',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'e97f372b-29bc-460b-bff6-35d2462411ff',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'category',
  );
  $terms[] = array(
    'name' => 'book shop/info shop/library',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'edad891e-151a-4219-9822-39c7dcff6a4f',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'category',
  );
  $terms[] = array(
    'name' => 'work space/diy',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'fc1d0760-6f0c-4239-be54-00ba7b97b965',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'category',
  );
  $terms[] = array(
    'name' => 'music',
    'description' => '',
    'format' => 'plain_text',
    'weight' => 0,
    'uuid' => 'ff3e2872-6140-4645-98f0-784d656a9c5c',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'category',
  );
  return $terms;
}
