<?php
/**
 * @file
 * radar_event.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function radar_event_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'node-event-field_offline'.
  $field_instances['node-event-field_offline'] = array(
    'bundle' => 'event',
    'default_value_function' => 'radar_event_entityreference_offline_prepopulate',
    'deleted' => 0,
    'description' => 'If available, the location is already filled in with the information from the group, but you can remove it and/or add another one.',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'entityreference',
        'settings' => array(
          'links' => 0,
          'use_content_language' => TRUE,
          'view_mode' => 'without_map',
        ),
        'type' => 'entityreference_entity_view',
        'weight' => 12,
      ),
      'full' => array(
        'label' => 'hidden',
        'module' => 'entityreference',
        'settings' => array(
          'links' => 0,
          'use_content_language' => TRUE,
          'view_mode' => 'without_map',
        ),
        'type' => 'entityreference_entity_view',
        'weight' => 11,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'ds_extras_field_template' => '',
    'entity_type' => 'node',
    'field_name' => 'field_offline',
    'label' => 'Locations',
    'required' => 0,
    'settings' => array(
      'behaviors' => array(
        'prepopulate' => array(
          'status' => 0,
        ),
      ),
      'entity_translation_sync' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'inline_entity_form',
      'settings' => array(
        'fields' => array(),
        'type_settings' => array(
          'allow_existing' => 1,
          'allow_new' => 1,
          'delete_references' => 0,
          'label_plural' => 'entities',
          'label_singular' => 'entity',
          'match_operator' => 'CONTAINS',
          'override_labels' => 0,
        ),
      ),
      'type' => 'inline_entity_form',
      'weight' => 9,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('If available, the location is already filled in with the information from the group, but you can remove it and/or add another one.');
  t('Locations');

  return $field_instances;
}
