<?php
// $Id: number_facets.module,v 1.8 2009/05/01 19:12:46 davidlesieur Exp $

/**
 * @file
 * Exposes CCK Number fields as facets.
 */

module_load_include('inc', 'cck_facets');

/**
 * Implementation of hook_cck_facets_collect().
 */
function number_facets_cck_facets_collect(&$facets, $field, $domain, $env, $arg = NULL) {
  if ($field['type'] == 'number_decimal' || $field['type'] == 'number_integer') {
    switch ($domain) {
      case 'facets':
        $facets[] = new cck_facet($field);
        break;

      case 'text':
        // Scan the given search text for a '{field_name}:{value}'
        // token, and create facets from it.
        if (!is_null($number = search_query_extract($arg, $field['field_name']))) {
          if (is_numeric($number)) {
            // Create an active facet with the value found in the search text.
            $category = new cck_facet_category($field, $number);
            $facets[] = new cck_facet($field, array($category));
          }
          // Remove the parsed text
          $arg = search_query_insert($arg, $field['field_name']);
        }
        break;

      case 'node':
        if (isset($arg->{$field['field_name']}) && is_array($arg->{$field['field_name']})) {
          // Iterate through the field's multiple values.
          foreach ($arg->{$field['field_name']} as $item) {
            $value = array_shift($item);
            if (is_numeric($value)) {
              $category = new cck_facet_category($field, $value);
              $facets[] = new cck_facet($field, array($category));
            }
          }
        }
        break;
    }
  }
  return $arg;
}

